version: '3.9'

services:
  auth-service:
    image: auth-srv:v2
    container_name: auth-service
    restart: always
    ports:
      - "3000:3000"

    env_file:
      - .env

    environment:
      PORT: 3000

    networks:
      - platform-network

networks:
  platform-network:
    external: true