services:
 
  # 📱 Number Verification Service
  number-verification:
   # build: ./number-verification-service
    image: number-verification-srv:v2
    container_name: number-verification
    ports:
      - "9091:9091"
    env_file:
      - .env
    
    restart: always
    networks:
      - platform-network

networks:
  platform-network:
    external: true     

